### ISSUE TITLE
not working on OSX 10.8

### ISSUE THREAD

**Issue by beej** [locomojis/Chromoji#10]
i'm using OSX 10.8.2 w/ Chrome 25.0.1364.99 and Chromoji 1.1.2

with all character sets enabled, when i look at the tweet at http://chromoji.blogspot.com/ i see the box instead of the winky face :(

**Comment by RobJDavey** [comment]
Are you talking about [this Tweet](https://twitter.com/RobJDavey/status/302526332200443904)?

Do you see the emoji OK if you look at [this page](http://www.grumdrig.com/emoji-list/)?
With all the sets enabled you should see every image on that page with no "box" characters.

**Comment by RobJDavey** [comment]
As I have not heard back from you I will assume that v1.2 (e3cee5de75626bb489d180a12bc1290edcac4338) has fixed your issues. If not I will re-open this after you reply.
