### ISSUE TITLE
Create Promotional tile images

### ISSUE THREAD

**Issue by RobJDavey** [locomojis/Chromoji#16]
Three promotional tile images are required:
- Small tile - 440x280
- Large tile - 920x680
- Marquee - 1400x560

**Comment by RobJDavey** [comment]
The small tile image was added in 88a4205.

**Comment by locomojis** [comment]
New promo images have been created.

**Comment by locomojis** [comment]
![promo-all-preview](https://f.cloud.github.com/assets/6598605/2119862/7363c480-9190-11e3-8544-8a7198166845.png)
