### ISSUE TITLE
Chromoji Doesn't Work Inside Tweetdeck Extension

### ISSUE THREAD

**Issue by soberstadt** [locomojis/Chromoji#17]
Emojis work fine in the web version of tweetdeck (web.tweetdeck.com) but don't when using the Chrome Extension (https://chrome.google.com/webstore/detail/tweetdeck/hbdpomandigafcibbmofojjchbcdagbl).

I don't understand the full extent of Chrome Extensions, but there is no address in the address bar, indicating a local page. LastPass doesn't work there either, so it may be a lost cause.

**Comment by RobJDavey** [comment]
Although not visible in Chrome by default, the address is actually **chrome-extension://hbdpomandigafcibbmofojjchbcdagbl/web/templates/default.html**.
No content scripts are run within these apps so there is no way for me to get the emoji in there that I know of.
