### ISSUE TITLE
Please, add black-list of sites.

### ISSUE THREAD

**Issue by s0snooley** [locomojis/Chromoji#19]
Please, create black list for sites, where this plugin will not replace smilies.
vk.com originally use emoji, and smiles displayed crooked with this plugin.

![emoji](https://f.cloud.github.com/assets/4379229/478733/02718bb6-b803-11e2-9aa8-435c69df8513.jpg)

**Comment by s0snooley** [comment]
Finally I did it myself :smile: 

Added: black list, size select
Changed element class, class "emoji" conflicted with some sites.

Here is download link, just change files in extension folder: http://rghost.ru/45861294

![emoji-settings](https://f.cloud.github.com/assets/4379229/479445/8620617a-b813-11e2-89f7-a93869edbcf9.jpg)

**Comment by RobJDavey** [comment]
Hi @s0snooley, please send the code to me as a pull request, then I can check it and merge it here on GitHub.

**Comment by s0snooley** [comment]
@RobJDavey I registered today and I don't know how to do it, sorry.
UPD: I figured out how to do this)
