### ISSUE TITLE
Emoji size issue

### ISSUE THREAD

**Issue by RobJDavey** [locomojis/Chromoji#22]
User left the following comment in a review:

> Runs great! This is exactly what I've been looking for! **However, it is hard to see the emojis because they are so small. This could be because of my HD screen, but it would be nice if each emoji was larger to make it easier to differentiate between like emojis.**

Investigation needed into the display of emoji on HD screens.

**Comment by aorchanian** [comment]
Looking at the emojis I have used in my tweets, it is hard for me to clearly see each picture. It is especially difficult to differentiate the yellow smiley faces.

![image](https://f.cloud.github.com/assets/4528921/564533/51d94710-c574-11e2-91bd-309ef25f085b.png)

**Comment by RobJDavey** [comment]
I think I will look at adding a "scale" setting to the emoji which will allow you to choose a larger scale for them. I'll try to get this into a release soon.

**Comment by aorchanian** [comment]
I think that's a great idea. Thanks for your help!
