### ISSUE TITLE
Emoji not shown in text box

### ISSUE THREAD

**Issue by RobJDavey** [locomojis/Chromoji#23]
One user has complained that emoji is not shown in a text box.
This is actually deliberate as usually user will not want the text box to get parsed while they are trying to write tweets, however I will need to investigate whether it is possible to enable this for users such as the one experiencing the issue.
In their situation the text box actually contains the output from a chat conversation, and is not an input for live text, in which case this may be a perfectly valid place for them to view emoji.
I will attempt to add an option in that will cause emoji in these areas to be rendered (however I am not sure this will ever work properly for emoji that is within a pure text box as we use images, not font items (as iOS and Mac OS X does).

**Comment by ticky** [comment]
I don't believe this will be possible. It's not possible to put HTML inside a text box element, and overlaying is challenging - you would have to replace the characters with something of equal width, which isn't necessarily possible, and somehow know when to return the value to its natural one for submission. Not to mention the challenge of working out positioning.
