### ISSUE TITLE
How to get it on Facebook

### ISSUE THREAD

**Issue by Kini101** [locomojis/Chromoji#25]
Hi i have download chromoji for 2 days now. I am not seeing it on facebook. How do I get it on Facebook?

**Comment by RobJDavey** [comment]
Please can you provide a specific example of where this has occurred, preferably with screenshots or links.
Chromoji will render on Facebook posts in places where Facebook do not replace the emoji with their own symbols, however some emoji symbols Facebook have their own images for which are inserted before Chromoji can run.
Here is a screenshot of some emoji from one of my Facebook posts.
![image](https://f.cloud.github.com/assets/884913/742811/79aae098-e3d6-11e2-898f-92ae936e2324.png)

**Comment by RobJDavey** [comment]
Assumed fixed as no response.
