### ISSUE TITLE
Chromoji causes YouTube HTML5 videos to end abruptly

### ISSUE THREAD

**Issue by navarr** [locomojis/Chromoji#27]
Chromoji causes YouTube videos (when a user is in the HTML5 Trial) to end within the first couple seconds.

Steps to reproduce:
- Install latest version of Chromoji
- Join [HTML5 Trial](http://www.youtube.com/html5)
- Load an [HTML5 Video](http://www.youtube.com/watch?v=drq_ww7Ytzw)

What should happen:
- Video plays fully through.

What does happen:
- Video plays for a little bit and then skips to the end.  Attempt to start the video by repositioning the buffer causes it to play, but the buffer fails to continue loading.

**Comment by keepevets** [comment]
also getting this same issue, temporarily fixed it by blacklisting youtube.com in the extension options

**Comment by locomojis** [comment]
Is this still happening with the new version? (you should've got an auto update from the Web Store)
Thanks!

**Comment by navarr** [comment]
An initial test of the instructions shows it to be working.  I think it's safe to say that the issue is likely resolved.

**Comment by locomojis** [comment]
Cool. Feel free to report any problems you may find in the future!

Thank you
