### ISSUE TITLE
Emojis don't display correctly in Disqus chats

### ISSUE THREAD

**Issue by raaomoka** [locomojis/Chromoji#30]
Hi, love the idea behind Chromoji; it solves one of the main reasons I keep thinking about IE on my Surface Pro. However, there seems to be still a bit of rendering problem on a few websites. On my old laptop, running Vista x64-Bit (soon to Se7en x64-Bit), while reading some news, I came across this webpage: http://goo.gl/pVufi9

Notice "aidan harris" disqus comment; it displays a box in place of the emoji. Not sure if this is the same case on Windows 8 and can't check at the moment, but on my iPhone, it renders it correctly as the WINKING FACE emoji. Could it be some incompatibility with Disqus?

**Comment by raaomoka** [comment]
Just an update (if anyone is actually looking into this issue), the same thing happens on Windows 8, regardless if I have the "Use native font" option enabled or not. The emoji doesn't display properly in Discus chats.

**Comment by locomojis** [comment]
It's fixed in the next version. 

Thank you
