### ISSUE TITLE
Enable for Google Hangout Emojis

### ISSUE THREAD

**Issue by asperdx** [locomojis/Chromoji#35]
http://www.cypressnorth.com/wp-content/uploads/2013/05/Google-Hangout-Emojis.jpg

I think for Chrome, there should be the Emojis used for Google Hangout at least as an option. This is mostly because they look 10000000x better.

Please and thank you

**Comment by locomojis** [comment]
Whether they look better is debatable but I may consider adding custom mappings to the Options page.

Do you have a full mapping table somewhere to the images?

**Comment by locomojis** [comment]
Ah, now I can see you have your fork with the images. Nice :)

**Comment by navarr** [comment]
@thesoberrussian Since you've already done all the very hard work I'm going to fork you and see if I can make some modifications to make the amount of work @locomojis has to do for this to be an option little to none.

I was in the process of doing the same thing and am very glad to see somebody has already done all the hard work.

**Comment by asperdx** [comment]
@navarr The only slight problem is I never reduced the resolution from when I pulled it from the Hangouts.apk and I think it might slow down performance. At the time, that's all the resources I had. The file names weren't the same either, had to rename most of them.

**Comment by navarr** [comment]
@thesoberrussian I'll run a test.  Worst comes to worst I'll run them through a script to put them at the same size.

**Comment by locomojis** [comment]
This is finally getting merged. Big kudos for manually renaming them.

Only problem is that the number symbols 0-9 are missing.

Namely: `"31-20e3","32-20e3","33-20e3","34-20e3","35-20e3","36-20e3","37-20e3","38-20e3","39-20e3","30-20e3"`

Can you guys look into those?

(you can check how they should look here: http://emojipedia.org/google-emoji-list/)

![numbers](https://cloud.githubusercontent.com/assets/6598605/4592063/a54e501e-5076-11e4-8ee7-c75af46fd841.png)

**Comment by navarr** [comment]
Those symbols don't exist in the Hangouts emoji dialect, unfortunately.

**Comment by locomojis** [comment]
Ok let's leave them out for now. Maybe later I'll make something for them in the style of the number 10.

You can check out the new version in the Chrome Web Store (2.3.0)

**Comment by navarr** [comment]
Is there a reason updates aren't being pushed out to the github repo?
