### ISSUE TITLE
Increased CPU / Freeze with large HTML Files

### ISSUE THREAD

**Issue by sukima** [locomojis/Chromoji#36]
I went to look at a large [file in Github](https://github.com/jquery/jquery/blob/master/build/r.js) and the tab froze and eventually  asked me to kill it. I ran a profiler on the page and found that until I stopped the profiling 77% of the CPU was dedicated to the `emoji.js` script:

![screen shot 2013-08-23 at 9 29 10 am](https://f.cloud.github.com/assets/70075/1016355/1c9a4ca0-0bf8-11e3-8d65-aa0d7baf6997.png)

Maybe there is a way to break out of the workload so that the UI doesn't get blocked on large calculations.

**Comment by locomojis** [comment]
The new version has an awesome speedup.  :-)
Be sure to check it out.
