### ISSUE TITLE
Pasting emojis

### ISSUE THREAD

**Issue by kitkat15** [locomojis/Chromoji#38]
I have another app(show me emoji) I was using prior to this that allowed me to to copy the codex for an emoji and paste it and it would show up. Now with this when I paste the same codex in a text box it disappears i'm assuming because this converts the codex to images which are not rendered in a text box like on twitter. Such 
I say this with the suggestion that You ignore rendering in text boxes. This way if I get an emoji and copy it from somewhere and paste it in a text box it doesn't disappear

**Comment by locomojis** [comment]
Is this still happening with the new version? (you should've got an auto update from the Web Store)

Thank you!

**Comment by locomojis** [comment]
I checked it and it now works correctly.
