### ISSUE TITLE
Denying load of chrome-extension://cahedbegdkagmcjfolhdlechbkeaieki/jquery.min.map on Chromium 29

### ISSUE THREAD

**Issue by m13253** [locomojis/Chromoji#41]
The message on the JavaScript console:
Denying load of chrome-extension://cahedbegdkagmcjfolhdlechbkeaieki/jquery.min.map. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

Chromium 29.0.1547.76 (223446) on Linux

I think I this information is enough. Call me if you need more.

**Comment by graysky** [comment]
I'm seeing this as well. Chrome 31.0.1650.63 on OSX Mavericks.

**Comment by engstrom** [comment]
I have the same message on Chrome Version 31.0.1650.63 on OSX 10.9.
