### ISSUE TITLE
How do I use the Chromoji extension for Chrome?  No icon is showing up by the address bar and there are no >> chevrons to expand...?

### ISSUE THREAD

**Issue by gasmithjr** [locomojis/Chromoji#48]

**Comment by dccarroll** [comment]
You can view the extensions on the extensions page (chrome://extensions/). It doesn't have any settings - so it should "just work" after being installed.

**Comment by gasmithjr** [comment]
Well, then, how do you pull up the symbols to display and choose them on your computer?  I am new at this, but I don't have any icon showing next to the address bar like I thought I should, but when I go to extensions, it shows that chromoji is installed and enabled.

Thanks, G.A.

**Comment by RobJDavey** [comment]
Hi,

Chromoji does not currently include an emoji keyboard.
It is a passive extension only for the real time in-line display of emoji
on webpages.

Thanks,

Robert Davey

On 11 Jan 2014, at 17:55, gasmithjr notifications@github.com wrote:

Well, then, how do you pull up the symbols to display and choose them on
your computer? I am new at this, but I don't have any icon showing next to
the address bar like I thought I should, but when I go to extensions, it
shows that chromoji is installed and enabled.

Thanks, G.A.

**Comment by laike9m** [comment]
Does not work on Mac Chrome 42, no icon in my toolbar though it's enabled.
