### ISSUE TITLE
Causes issues with Reddit Enhancement Suite

### ISSUE THREAD

**Issue by johnstraka** [locomojis/Chromoji#49]
Much of the extra functionality ("view images" link, "hide child comments" link) added by the Reddit Enhancement Suite extension is, for some reason, randomly broken by Chromoji.

Not sure what else I might provide to help debug it, or if you'll bother, but thought I'd post it regardless.

**Comment by locomojis** [comment]
Can you check the new version (it should auto update from the Web Store)? Thank you!

**Comment by locomojis** [comment]
It has been reported on reddit that this is now Fixed!

http://www.reddit.com/r/RESissues/comments/1wokvz/bug_inline_image_viewer_not_working_on_frontpage/cf41cy1

http://www.reddit.com/r/RESissues/comments/1wv3ny/sticky_chromoji_is_breaking_redditres_on_windows/cffl7c7
