### ISSUE TITLE
Add Emoji Keyboard support

### ISSUE THREAD

**Issue by RobJDavey** [locomojis/Chromoji#5]
Add support to allow typing of emoji character within the browser.

**Comment by soberstadt** [comment]
From my research tonight, this will be pretty hard. My initial thought was to to it in a popout (which I'm actually working on right now). To actually get the character into an input box would require getting from that popout page's sandbox into the current pages sandbox. I'm currently working on implementing copying the image to the clipboard for easy pasting.

**Comment by RobJDavey** [comment]
I've already started working on a way of doing this using an element inserted into the page the user is looking at.
From there it is very easy to get hold of the current input being edited and insert data.
As it is already inside the page there is no need to worry about the sandbox.

I like the idea of copying one of the images putting the character code onto the clipboard. Would be quite useful.

**Comment by soberstadt** [comment]
I got stuff working last night. I'll push it up after a little refactoring.

**Comment by soberstadt** [comment]
Pull request: #18

**Comment by navarr** [comment]
My two cents: A picker like Apple/Google Hangouts has would be lovely.

**Comment by locomojis** [comment]
This will be included in the next version. It's currently being rolled out to users gradually (to make sure there are no compatibility issues).

It has both copy and paste functionality (if you have a text box selected).

**Comment by navarr** [comment]
Oh it's absolutely lovely.  If I may be so bold, you might consider making it embed itself in the page when the button is clicked.  That way it acts like an on-screen virtual keyboard.  (Even better if it's draggable).

An example of what I'm talking about is already done by [Emojify](https://chrome.google.com/webstore/detail/lpkndkffkmhcdkkdmeeelikmadjjmebe).  

Either way, your work on this project is awesome and appreciated.

**Comment by locomojis** [comment]
Yes I know about that extension. I'll think about this. Thanks for the suggestion!
