### ISSUE TITLE
Issue with Instagram web feed

### ISSUE THREAD

**Issue by csihar** [locomojis/Chromoji#52]
When viewing my feed at instagram.com, I've found that recently the page has been breaking after a few seconds after load when Chromoji is enabled. Certain page elements are duplicated and/or misaligned, and looking at the console shows multiple "Uncaught Error: Invariant Violation" warnings. I'm using the latest stable version of Chrome on Win 7.

**Comment by locomojis** [comment]
Please check the new version. Thanks!
