### ISSUE TITLE
Gmail issues

### ISSUE THREAD

**Issue by Pau1ey** [locomojis/Chromoji#53]
Cannot click on anything at all. It's definitely because of the Chromoji plugin, as when disabled it works properly. Maybe related to the characters 會員 in the from address on some Ebay emails I have just received, other emails are old and I didn't have issues before.

**Comment by locomojis** [comment]
Is this still happening with the new version? (you should've got an auto update from the Web Store)

If it is: Can you send me those emails so I can reproduce this issue?

I have a gmail account at 'locomojis'.  Thanks!

**Comment by Pau1ey** [comment]
Hi, thanks for the quick reply! It seems to be working ok now. This is what
I show as the version: Chromoji - Emoji for Google Chrome(tm) 1.5.8.

**Comment by locomojis** [comment]
cool. 

If you have any problems again feel free to open a new issue.

Thank you!
