### ISSUE TITLE
can you support this?

### ISSUE THREAD

**Issue by Marukon** [locomojis/Chromoji#59]
https://chrome.google.com/webstore/detail/google-keep-notes-and-lis/hmjkmjkepdijhoojdojkdfohbdgmmhki

**Comment by locomojis** [comment]
It's troublesome because the browser toolbar (with Chromoji) is not visible within apps.

**Comment by navarr** [comment]
Perhaps we can swap from a button on the toolbar to a right click menu addition? Though I'm not sure if that works within apps or not.

**Comment by Marukon** [comment]
Ok.we can have a test ,thank you!

发件人: Navarr Barnier [mailto:notifications@github.com] 
发送时间: 2014年10月11日 3:25
收件人: locomojis/Chromoji
抄送: zhangxuhu
主题: Re: [Chromoji] can you support this? (#59)

Perhaps we can swap from a button on the toolbar to a right click menu addition? Though I'm not sure if that works within apps or not.
